apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: react-ssr-template
  title: React SSR Template
  description: Create a website powered with Next.js
  tags:
    - recommended
    - react
spec:
  owner: web@example.com
  type: website
  parameters:
    - title: Provide some simple information
      required:
        - component_id
        - repository_name
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
        repository_name:
          title: Azure DevOps Repo Name
          type: string
          description: Azure DevOps Repo name for your application. If your domain may involve multiple applications, please think of a unique but easily identifiable repo name. 
            
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
          - .github/workflows/*
        values:
          component_id: '{{ parameters.component_id }}'
          description: '{{ parameters.description }}'
          destination: 'dev.azure.com?owner=ProductionAI&repo={{ parameters.repository_name }}&organization=basf4dev'
          owner: 'team-singularity'

    - id: publish
      name: Publish
      action: publish:azure
      input:
        repoUrl: 'dev.azure.com?owner=ProductionAI&repo={{ parameters.repository_name }}&organization=basf4dev'
        description: 'This is {{ parameters.component_id }}'
        defaultBranch: 'main'

  output:
    remoteUrl: '{{ steps.publish.output.remoteUrl }}'    
    repoContentsUrl: '{{ steps.publish.output.repoContentsUrl }}'
