apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: react-ssr-template
  title: React SSR Template
  description: Create a website powered with Next.js
  tags:
    - recommended
    - react
spec:
  owner: web@example.com
  type: website
  parameters:
    - title: Provide some simple information
      required:
        - component_id
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - dev.azure.com
            
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
          - .github/workflows/*
        values:
          component_id: '{{ parameters.component_id }}'
          description: '{{ parameters.description }}'
          destination: '{{ parseRepoUrl parameters.repoUrl }}'
          owner: 'team-singularity'

    - id: publish
      name: Publish
      action: publish:azure
      input:
        repoUrl: '{{ parameters.repoUrl }}'
        description: 'This is {{ parameters.component_id }}'
        defaultBranch: 'main'

  output:
    remoteUrl: '{{ steps.publish.output.remoteUrl }}'    
    repoContentsUrl: '{{ steps.publish.output.repoContentsUrl }}'
